### ISSUE TITLE
More LED functions / Link to volume level?

### ISSUE THREAD

**Issue by ghost** [stefansundin/powermate-linux#20]
So currently it can be turned on and off.  I'm not sure if there is a way to change the brightness.

Also I had an idea of linking the current brightness to the current volume level.  Of course, I'm not sure how to do that since I can't code at all beyond basic scripting, but I wanted to throw the idea out there.  I think it would be very useful if thrown on a RaspberryPie that isn't using an actual display.  Obviously if it's currently playing something that wouldn't be necessary but if it's stopped/paused then it would be useful.  Also I just think it'd be neat in general too.

**Comment by stefansundin** [comment]
Hi. The LED brightness is already linked to the volume level.

This is the relevant code: https://github.com/stefansundin/powermate-linux/blob/a5aed4058e4139c9a316419a679c4aa494c51e07/main.c#L63-L72

**Comment by ghost** [comment]
Strange, as it wasn't working for me but seems to be fine now.  Either a reboot fixed it or I just didn't turn it down far enough to notice.  I'm betting the latter although I could have sworn I tested that.

Anyway thanks, and sorry for bugging you.

**Comment by stefansundin** [comment]
It might have been that you needed to unplug and plug the device back in after installing the udev rule. If the device is plugged in before the udev rule is installed then the device won't be accessible by the program until that is done.
