### ISSUE TITLE
wheel sensitivity

### ISSUE THREAD

**Issue by f2107** [stefansundin/powermate-linux#7]
Hi, this is not an issue ... it is more a question. Together with evrouter is it possible to setup the wheel sensitivity? Any experiences?

Usecase: 
* execute commands on turn the wheel left or right... actually the commands are executed too often (cause of sensitivity of the wheel)

Thanks for any hints.

Regards;

**Comment by stefansundin** [comment]
Hi. For now you will have to compile the program yourself. You have to change the variable `p` which says how many percentage points to increase/decrease. It's only used in one place, to calculate the step in the unit that pulseaudio is using. I don't remember if I tested `p` lower than 1 (you'd have to make it a float), so if that doesn't work as expected, then you might have to change it in that other place.

Here are the source code locations:
- https://github.com/stefansundin/powermate-linux/blob/c6ff4c138f2c652f7feb714a40e33242efaf2527/main.c#L14
- https://github.com/stefansundin/powermate-linux/blob/c6ff4c138f2c652f7feb714a40e33242efaf2527/main.c#L161

Should probably add a configuration file to allow this to be changed without having to recompile the program.

**Comment by f2107** [comment]
Thanks. I will figure it out.

**Comment by stefansundin** [comment]
@f2107 I released a new version and this is now easy peasy to change in a config file: https://github.com/stefansundin/powermate-linux/blob/e99d1c289d678266cd9e89462b770fb06af56a01/powermate.toml#L12-L13

💥
