### ISSUE TITLE
Custom actions?

### ISSUE THREAD

**Issue by howels** [stefansundin/powermate-linux#8]
Would you consider adding custom actions? I used to use the long-press to suspend the PC in Windows for example.

**Comment by stefansundin** [comment]
Hi!

That sounds like a good idea.. #7 needs a configuration file too.

Do you think it would be enough to be able to launch an arbitrary program?

Example config file:

```
long_press_ms=5000
long_press_command=systemctl suspend
clock_wise_command=switch_workspace_clock_wise
```

So if `long_press_command` is specified, then the built-in "movie mode" functionality will be disabled. Same with `clock_wise_command` and volume.

I am not sure what parsing library I should use. I think I might make it a toml file and I suspect there are good C libraries for that.

**Comment by howels** [comment]
Absolutely, calling an arbitrary program could include dbus commands which allows for most desktop actions.

**Comment by stefansundin** [comment]
Hi @howels. I have released a new version now that lets you do this. Let me know if it works the way you want or if there's anything missing.

**Comment by howels** [comment]
@stefansundin thanks a lot, that works perfectly!
